#!/bin/sh
#
# Copyright 2025 Michael Reilly <mreilly@mreilly.dev>
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the names of the copyright holders nor the names of the
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e -v

# Remove acronyms, all-uppercase words, and words with 3 or fewer letters
comm -23 unix/common.txt unix/acronyms.txt | grep -v -E '\b[[:upper:]]+\b' | grep '....' > credgen_words.tmp

# Remove lines with numbers and symbols
sed -i -e '/[1234567890]/d' credgen_words.tmp
sed -i -e '/`/d' credgen_words.tmp
sed -i -e '/~/d' credgen_words.tmp
sed -i -e '/!/d' credgen_words.tmp
sed -i -e '/@/d' credgen_words.tmp
sed -i -e '/#/d' credgen_words.tmp
sed -i -e '/\$/d' credgen_words.tmp
sed -i -e '/%/d' credgen_words.tmp
sed -i -e '/\^/d' credgen_words.tmp
sed -i -e '/\&/d' credgen_words.tmp
sed -i -e '/\*/d' credgen_words.tmp
sed -i -e '/(/d' credgen_words.tmp
sed -i -e '/)/d' credgen_words.tmp
sed -i -e '/-/d' credgen_words.tmp
sed -i -e '/_/d' credgen_words.tmp
sed -i -e '/=/d' credgen_words.tmp
sed -i -e '/+/d' credgen_words.tmp
sed -i -e '/\[/d' credgen_words.tmp
sed -i -e '/{/d' credgen_words.tmp
sed -i -e '/\]/d' credgen_words.tmp
sed -i -e '/}/d' credgen_words.tmp
sed -i -e '/\\/d' credgen_words.tmp
sed -i -e '/|/d' credgen_words.tmp
sed -i -e '/;/d' credgen_words.tmp
sed -i -e '/:/d' credgen_words.tmp
sed -i -e "/'/d" credgen_words.tmp
sed -i -e '/"/d' credgen_words.tmp
sed -i -e '/,/d' credgen_words.tmp
sed -i -e '/</d' credgen_words.tmp
sed -i -e '/\./d' credgen_words.tmp
sed -i -e '/>/d' credgen_words.tmp
sed -i -e '/\//d' credgen_words.tmp
sed -i -e '/?/d' credgen_words.tmp
sed -i -e '/ /d' credgen_words.tmp

# Lowercase everything
tr '[:upper:]' '[:lower:]' <credgen_words.tmp | sort | uniq >credgen_words.txt

# Remove tmpfiles
rm credgen_words.tmp

# Add data to header
Output="../src/credgen_words.h"
cat sources > $Output
xxd -i credgen_words.txt >> $Output

# Format header and add NUL delimiters
sed -i -e "/unsigned int/d" $Output
sed -i -e "s/unsigned char/const char/g" $Output
sed -i -e "s/0x0a$/0x00, 0x00/g" $Output
sed -i -e "s/0x0a/0x00/g" $Output

# Done
printf "Words file generation completed\n\n"
